### ISSUE TITLE
[NEW VARIATION]

### ISSUE THREAD

**Issue by pgblu** [vopani/sudokuib#1]
## Sudoku Variation Name
Parity Party

## Sudoku Rules (Optional but helpful if provided with text or a link)
Clues along the edge of the grid indicate the sum of digits from that vantage point up to and including the first odd or first even digit. Clues less than 10 could, but need not, be equal to the first seen digit (i.e., zero odds and one even, or vice versa).
https://logic-masters.de/Raetselportal/Suche/erweitert.php?tag_id=9315

**Comment by pgblu** [comment]
Suggested tags: math, parity

**Comment by vopani** [comment]
Thanks @pgblu , I'll add this.

I'm also in the process of tagging inventors to the variants. I see on the LMD portal that you are the inventor of this variant. Could you please share what name to use for the credit? `Georg-Philipp Blume`? And also the year of invention if possible. Thanks again!

**Comment by pgblu** [comment]
Yes, I don't really use 'Georg', you can just call me Philipp Blume. The constraint was developed in March 2020.

**Comment by vopani** [comment]
Updated, thanks a lot!
