### ISSUE TITLE
[NEW VARIATION]

### ISSUE THREAD

**Issue by pgblu** [vopani/sudokuib#2]
## Sudoku Variation Name
XY-Differences

## Sudoku Rules (Optional but helpful if provided with text or a link)
A diamond between horizontally adjacent cells means that the digits in those cells exhibit a difference equal to the leftmost digit in that row. A diamond between vertically adjacent cells means that the digtis in those cells exhibit a difference equal to the topmost digit in that column. If two cells have no diamond between them, then this difference relation must not pertain.
https://logic-masters.de/Raetselportal/Suche/erweitert.php?tag_id=9331

**Comment by pgblu** [comment]
Suggested tags: math, neighbour

**Comment by pgblu** [comment]
Invented June 2020 by Philipp Blume

**Comment by vopani** [comment]
Updated, thanks a lot!
